#pragma once
#include <numbers>
#include <array>

/*
  the source file that defines these magics are generated by running the
  magic-generation and magic-conversion utilities.

  current ones are generated by yours truly on my home server over the course
  of a couple of days, it doesn't take too long to get magics but getting
  magics that compress the bitboards takes time
*/

namespace Chess::MagicBitboards
{
  extern const uint64_t orthMasks[64];
  extern const uint64_t orthMagics[64];
  extern const uint8_t orthShifts[64];
  extern const uint64_t *orthMovesets[64];

  extern const uint64_t diagMasks[64];
  extern const uint64_t diagMagics[64];
  extern const uint8_t diagShifts[64];
  extern const uint64_t *diagMovesets[64];
}
