#include <unistd.h>
#include <fstream>
#include <iostream>
#include <map>
#include <array>
#include <cinttypes>

struct MagicMapEntry
{
  int shift{0};
  uint64_t magic{0};
  std::map<uint64_t, uint64_t> moveMap;
};

int main(int argc, char **argv)
{
  char opt;
  std::ifstream input;
  std::ofstream output;
  while ((opt = getopt(argc, argv, "i:o:")) != -1)
  {
    switch (opt)
    {
    case 'i':
      input = std::ifstream(optarg);
      break;
    case 'o':
      std::remove(optarg);
      output = std::ofstream(optarg);
      break;
    }
  }
  if (!input || !output)
  {
    std::cout << "Must specify input and output file.\n";
    return -1;
  }

  std::array<std::pair<MagicMapEntry, MagicMapEntry>, 64> magicMap{};

  // this format could be improved like 17-fold however. there is no need.
  input.ignore(); // '{'
  for (int i{0}; i < 64; i++)
  {
    uint64_t magic{0};
    input >> magic;
    magicMap[i].first.magic = magic;
    input.ignore(4); // 'ull,' / 'ull}'
  }
  input.ignore(2); // '\n{'
  for (int i{0}; i < 64; i++)
  {
    uint shift{0};
    input >> shift;
    magicMap[i].first.shift = shift;
    input.ignore(2); // 'u,' / 'u}'
  }
  input.ignore(2); // '\n{'
  for (int i{0}; i < 64; i++)
  {
    uint64_t index{0};
    std::map<uint64_t, uint64_t> map{};
    while (!input.eof() && input.peek() != '}')
    {
      input.ignore(1); // '{' / ','
      uint64_t bitboard{0};
      input >> bitboard;
      if (bitboard > 0ull)
        map[index] = bitboard;
      input.ignore(3); // 'ull'
      index++;
    }
    magicMap[i].first.moveMap = map;
    input.ignore(3); // '},\n'
  }
  input.ignore(2); // '\n{'

  for (int i{0}; i < 64; i++)
  {
    uint64_t magic{0};
    input >> magic;
    magicMap[i].second.magic = magic;
    input.ignore(4); // 'ull,' / 'ull}'
  }
  input.ignore(2); // '\n{'
  for (int i{0}; i < 64; i++)
  {
    uint shift{0};
    input >> shift;
    magicMap[i].second.shift = shift;
    input.ignore(2); // 'u,' \ 'u}'
  }
  input.ignore(2); // '\n{'
  for (int i{0}; i < 64; i++)
  {
    uint64_t index{0};
    std::map<uint64_t, uint64_t> map{};
    while (!input.eof() && input.peek() != '}')
    {
      input.ignore(1); // '{' / ','
      uint64_t bitboard{0};
      input >> bitboard;
      if (bitboard > 0ull)
        map[index] = bitboard;
      input.ignore(3); // 'ull'
      index++;
    }
    magicMap[i].second.moveMap = map;
    input.ignore(3); // '},\n'
  }

  /*
  format:
  uint64_t orthMagics[64] = {orth magic, orth magic, ... (x 64)}
  uint8_t orthShifts[64] = {orth shift, orth shift, ... (x 64)}
  uint64_t allOrthMovesets[] = {bitboard, bitboard, ...}
  uint64_t *orthMovesets[64] = {numx + orth index, nums + orth index, ... (x 64)}
  (repeat for diagonal)
  */
  // write magics
  output << "/* code generated by magic-conversion, do not touch! */\n#include <cinttypes>\nuint64_t orthMagics[64] = {";
  for (int i{0}; i < 64; i++)
  {
    output << magicMap[i].first.magic << "ull";
    if (i < 63)
      output << ",";
  }
  output << "};\nuint8_t orthShifts[64] = {";
  for (int i{0}; i < 64; i++)
  {
    output << magicMap[i].first.shift << "u";
    if (i < 63)
      output << ",";
  }
  output << "};\nuint64_t allOrthMovesets[] = {";
  std::array<uint32_t, 63> orthOffsets{0};
  uint32_t currentOffset{0};
  for (int i{0}; i < 64; i++)
  {
    // set offsets for all other than first square, unneeded
    if (i > 0)
      orthOffsets[i - 1] = currentOffset;

    const auto &movesets = magicMap[i].first.moveMap;
    const uint32_t maxIndex = movesets.rbegin()->first;
    for (uint64_t j{0}; j <= maxIndex; j++)
    {
      if (movesets.contains(j))
        output << movesets.at(j) << "ull";
      else
        output << "0ull";
      if (j < maxIndex)
        output << ",";
    }

    // set first index of next set of movesets to one past last index (trust me)
    currentOffset += maxIndex + 1;
    if (i < 63)
      output << ",\n";
  }
  output << "};\nuint64_t *orthMovesets[64] = {allOrthMovesets,";
  // pointer arithmatic shenanigans
  for (int i{0}; i < 63; i++)
  {
    output << "allOrthMovesets + " << orthOffsets[i];
    if (i < 62)
      output << ",";
  }
  output << "};\nuint64_t diagMagics[64] = {";
  // yeah so just do all this again for diagonals ig
  for (int i{0}; i < 64; i++)
  {
    output << magicMap[i].second.magic << "ull";
    if (i < 63)
      output << ",";
  }
  output << "};\nuint8_t diagShifts[64] = {";
  for (int i{0}; i < 64; i++)
  {
    output << magicMap[i].second.shift << "u";
    if (i < 63)
      output << ",";
  }
  output << "};\nuint64_t allDiagMovesets[] = {";
  std::array<uint32_t, 63> diagOffsets{0};
  currentOffset = 0;
  for (int i{0}; i < 64; i++)
  {
    if (i > 0)
      diagOffsets[i - 1] = currentOffset;

    const auto &movesets = magicMap[i].second.moveMap;
    const uint32_t maxIndex = movesets.rbegin()->first;
    for (uint64_t j{0}; j <= maxIndex; j++)
    {
      if (movesets.contains(j))
        output << movesets.at(j) << "ull";
      else
        output << "0ull";
      if (j < maxIndex)
        output << ",";
    }

    currentOffset += maxIndex + 1;
    if (i < 63)
      output << ",\n";
  }
  output << "};\nuint64_t *diagMovesets[64] = {allDiagMovesets,";
  for (int i{0}; i < 63; i++)
  {
    output << "allDiagMovesets+" << diagOffsets[i];
    if (i < 62)
      output << ",";
  }
  output << "};\n";
}
