#include <unistd.h>
#include <fstream>
#include <iostream>
#include <map>
#include <array>
#include <cinttypes>
#include "bitboards.hpp"

struct MagicMapEntry
{
  int shift{0};
  uint64_t magic{0};
  std::map<uint64_t, uint64_t> moveMap;
};

int main(int argc, char **argv)
{
  char opt;
  std::ifstream input;
  std::ofstream output;
  while ((opt = getopt(argc, argv, "i:o:n:")) != -1)
  {
    switch (opt)
    {
    case 'i':
      input = std::ifstream(optarg);
      break;
    case 'o':
      std::remove(optarg);
      output = std::ofstream(optarg);
      break;
    }
  }
  if (!input || !output)
  {
    std::cout << "Must specify input and output file.\n";
    return -1;
  }

  std::array<std::pair<MagicMapEntry, MagicMapEntry>, 64> magicMap{};

  // this format could be improved like 17-fold however. there is no need.
  // 3 minutes later - screw it we ball
  uint64_t bitboard;
  for (int i{0}; i < 64; i++)
  {
    auto &[orth, diag] = magicMap[i];
    if (input.peek() == EOF)
    {
      std::cerr << "Malformed magic file!\n";
      return -1;
    }

    input >> orth.magic;
    input >> orth.shift;
    uint32_t orthIndex{0};
    while (input.peek() != ',' && input.peek() != EOF)
    {
      input >> bitboard;
      if (bitboard > 0ull)
        orth.moveMap[orthIndex] = bitboard;
      orthIndex++;
    }

    input.ignore(2);
    if (input.peek() == EOF)
    {
      std::cerr << "Malformed magic file!\n";
      return -1;
    }

    input >> diag.magic;
    input >> diag.shift;
    uint32_t diagIndex{0};
    while (input.peek() != ',' && input.peek() != EOF)
    {
      input >> bitboard;
      if (bitboard > 0ull)
        diag.moveMap[diagIndex] = bitboard;
      diagIndex++;
    }
    input.ignore(2);
  }

  /*
  format:
  uint64_t orthMagics[64] = {orth magic, orth magic, ... (x 64)}
  uint8_t orthShifts[64] = {orth shift, orth shift, ... (x 64)}
  uint64_t allOrthMovesets[] = {bitboard, bitboard, ...}
  uint64_t *orthMovesets[64] = {numx + orth index, nums + orth index, ... (x 64)}
  (repeat for diagonal)
  */
  // write magics
  output << "/* code generated by magic-conversion, do not touch! */\n#include <cinttypes>\n#include \"magicBitboards.hpp\"\nconst uint64_t Chess::MagicBitboards::orthMasks[64] = {";

  // output masks
  for (int i{0}; i < 64; i++)
  {
    output << orthOccupancyMasks[i] << "ull";
    if (i < 63)
      output << ",";
  }
  output << "};\nconst uint64_t Chess::MagicBitboards::orthMagics[64] = {";

  // output orthogonal magics
  for (int i{0}; i < 64; i++)
  {
    output << magicMap[i].first.magic << "ull";
    if (i < 63)
      output << ",";
  }
  output << "};\nconst uint8_t Chess::MagicBitboards::orthShifts[64] = {";

  // orthogonal shift values
  for (int i{0}; i < 64; i++)
  {
    output << magicMap[i].first.shift << "u";
    if (i < 63)
      output << ",";
  }
  output << "};\nconst uint64_t allOrthMovesets[] = {";

  // create all orthogonal moveset list
  std::array<uint32_t, 63> orthOffsets{0};
  uint32_t currentOffset{0};
  for (int i{0}; i < 64; i++)
  {
    // set offsets for all other than first square, unneeded
    if (i > 0)
      orthOffsets[i - 1] = currentOffset;

    const auto &movesets = magicMap[i].first.moveMap;
    const uint32_t maxIndex = movesets.rbegin()->first;
    for (uint64_t j{0}; j <= maxIndex; j++)
    {
      if (movesets.contains(j))
        output << movesets.at(j) << "ull";
      else
        output << "0ull";
      if (j < maxIndex)
        output << ",";
    }

    // set first index of next set of movesets to one past last index (trust me)
    currentOffset += maxIndex + 1;
    if (i < 63)
      output << ",\n";
  }

  // output individual square orth movesets list pointers
  output << "};\nconst uint64_t *Chess::MagicBitboards::orthMovesets[64] = {allOrthMovesets,";
  // pointer arithmatic shenanigans
  for (int i{0}; i < 63; i++)
  {
    output << "allOrthMovesets + " << orthOffsets[i];
    if (i < 62)
      output << ",";
  }

  // output diagonal masks
  output << "};\nconst uint64_t Chess::MagicBitboards::diagMasks[64] = {";
  for (int i{0}; i < 64; i++)
  {
    output << diagOccupancyMasks[i] << "ull";
    if (i < 63)
      output << ",";
  }

  output << "};\nconst uint64_t Chess::MagicBitboards::diagMagics[64] = {";
  // yeah so just do all this again for diagonals ig
  for (int i{0}; i < 64; i++)
  {
    output << magicMap[i].second.magic << "ull";
    if (i < 63)
      output << ",";
  }
  output << "};\nconst uint8_t Chess::MagicBitboards::diagShifts[64] = {";
  for (int i{0}; i < 64; i++)
  {
    output << magicMap[i].second.shift << "u";
    if (i < 63)
      output << ",";
  }
  output << "};\nconst uint64_t allDiagMovesets[] = {";
  std::array<uint32_t, 63> diagOffsets{0};
  currentOffset = 0;
  for (int i{0}; i < 64; i++)
  {
    if (i > 0)
      diagOffsets[i - 1] = currentOffset;

    const auto &movesets = magicMap[i].second.moveMap;
    const uint32_t maxIndex = movesets.rbegin()->first;
    for (uint64_t j{0}; j <= maxIndex; j++)
    {
      if (movesets.contains(j))
        output << movesets.at(j) << "ull";
      else
        output << "0ull";
      if (j < maxIndex)
        output << ",";
    }

    currentOffset += maxIndex + 1;
    if (i < 63)
      output << ",\n";
  }
  output << "};\nconst uint64_t *Chess::MagicBitboards::diagMovesets[64] = {allDiagMovesets,";
  for (int i{0}; i < 63; i++)
  {
    output << "allDiagMovesets+" << diagOffsets[i];
    if (i < 62)
      output << ",";
  }
  output << "};\n";
}
